### ISSUE TITLE
FEAT Add positivity constraint for `L1` and `L21` penalties

### ISSUE THREAD

**Issue by PABannier** [scikit-learn-contrib/skglm#107]

**Comment by mathurinm** [comment]
It could be done either by using a `PositiveL1` penalty (duplicates code but keeps L1 untouched) or adding a `positive` argument to L1 (that may confuse users that just care about a vanilla L1 penalty)

**Comment by PABannier** [comment]
I'd opt for the `positive` option (principles of least surprise, close to sklearn + less code to maintain).
