### ISSUE TITLE
DOC Write tutorial "How to add a datafit? How to add a penalty? in skglm"

### ISSUE THREAD

**Issue by PABannier** [scikit-learn-contrib/skglm#115]
I think that'd be a valuable addition for any newcomers wanting to add a custom datafit or penalty. Plus it's a great piece of doc to understand how `skglm` works behind the scenes.

**Comment by mathurinm** [comment]
We have https://contrib.scikit-learn.org/skglm/add.html with a link in the header but if you did not find it, we may need to think about a better way to emphasize it. Feel free to update the content itself too, now that we have progressed on solvers and API

**Comment by PABannier** [comment]
I was thinking about a more hands-on tutorial, like adding the Poisson datafit. We start from the formulation of the datafit, and derive all the necessary quantities and questions one would need to ask itself to add the datafit (e.g. is my datafit Lipschitz). A mix between maths and code actually.

**Comment by PABannier** [comment]
Also, I find the `raw_grad` and `raw_hessian` names very misleading, that's worth at least an explanation in the documentation and an example.

**Comment by Badr-MOUFAD** [comment]
I agree with @PABannier on having a hands-on tutorial on adding new datafit.
We can get inspired by the approach we followed to add Poisson or Gamma datafits.

**Comment by mathurinm** [comment]
Go for it !
