### ISSUE TITLE
MNT - Merge ``Lasso`` and ``WeightedLasso`` estimators

### ISSUE THREAD

**Issue by Badr-MOUFAD** [scikit-learn-contrib/skglm#122]
Following https://github.com/scikit-learn-contrib/skglm/pull/110#discussion_r1023792700,

`Lasso` and `WeightedLasso` estimators share the same implementation logic.
How `weights=None` is handled in the `WeightedLasso` estimator hints at merging the two estimators by adding a ``weights`` argument to Lasso.

To achieve that
- remove `WeightedLasso`
- add a `weights` argument in `Lasso` estimator
- handle `weighs` argument in `path` and `fit` methods

**Comment by PABannier** [comment]
How about `ElasticNet` ?

**Comment by Badr-MOUFAD** [comment]
I gave it a thought but I think we should have `Weighted_L1_plus_L2` to handle the three estimators in one.

**Comment by nilesh05apr** [comment]
Is this issue resolved? I would like to work on this.

**Comment by Badr-MOUFAD** [comment]
It still hasn't been resolved yet.
Go ahead, you have the support of the team.

**Comment by mathurinm** [comment]
I am -1 on this proposition :
- we need lasso for straightforward sklearn compatibility
- having weightedlasso makes it obvious that we support weights, while having it as a feature of Lasso would make it less visible
