### ISSUE TITLE
coef_ and intercept_ are deprecated for OneVsRestClassifier

### ISSUE THREAD

**Issue by glemaitre** [scikit-learn-contrib/skglm#13]
The following assignment will fail in scikit-learn 1.1:
https://github.com/scikit-learn-contrib/skglm/blob/main/skglm/estimators.py#L917

`coef_` and `intercept_` have been deprecated and are removed in scikit-learn 1.1.
Testing the RC on the code, break one of the tests.

**Comment by mathurinm** [comment]
Thanks a lot @glemaitre ! I suppose proceeding as in https://github.com/scikit-learn-contrib/skglm/blob/main/skglm/estimators.py#L262 would fix ?
