### ISSUE TITLE
FEAT - enable fitting ``Lasso``, ``WeightedLasso``, and ``ElasticNet`` with positivity constraint

### ISSUE THREAD

**Issue by Badr-MOUFAD** [scikit-learn-contrib/skglm#132]
Doable thanks to #110

To do so
1. Add a ``positive`` argument in the estimators
2. pass in the ``positive`` argument to the penalties

**Comment by PABannier** [comment]
It's done in my PR ;) (https://github.com/scikit-learn-contrib/skglm/pull/110/files#diff-5a55ebbdbb198f456b4549cc660c2b1e6fc838fd05424e8f4b7775239aed32b9R318)

**Comment by Badr-MOUFAD** [comment]
I confused it with passing in ``positive`` to subdiffdistance.
