### ISSUE TITLE
Please add option to GeneralizedLinearEstimator to not have an intercept 

### ISSUE THREAD

**Issue by pbeste18** [scikit-learn-contrib/skglm#139]

**Comment by PABannier** [comment]
Hello @pbeste18 ,

Thanks for posting this issue. Just to clarify what you are requesting: you want to fit a `GeneralizedLinearEstimator` without an intercept. This is already possible by passing a custom solver and disable `fit_intercept` like:

```python
clf = GeneralizedLinearEstimator(Quadratic(), L1(1.), solver=AndersonCD(fit_intercept=False))
```

The philosophy of `GeneralizedLinearEstimator` is to offer a generic interface to solve a wide range of smooth + non smooth optimization problems. Therefore we don't plan to expose solver parameters like `fit_intercept` directly in `GeneralizedLinearEstimator`.

I hope this clarifies your issue.

**Comment by pbeste18** [comment]
ah, lovely!  I'm really excited to use the library. I've been looking for something like this in python for years. Thanks for the speedy reply.
