### ISSUE TITLE
How to use the proximal operator of MCPenalty for model optimization?

### ISSUE THREAD

**Issue by Leon924** [scikit-learn-contrib/skglm#143]
Now, my situation is, to use MCP penalty for tackling with linear regression problem. Inside the API of MCPenalty class, the prox_1d method can be used to calculated to see its proximate value. Then, How to use this method when doing training?

**Comment by QB3** [comment]
Hello @Leon924 , if you want to use the MCP-penalized linear regression you can directly use the scikit-learn-like estimator `MCPRgression` https://contrib.scikit-learn.org/skglm/generated/skglm.MCPRegression.html#

It follows the same API as scikit-learn. Let us know if it works for you or if you need more details!

**Comment by mathurinm** [comment]
Hi @Leon924, does using `MCPRegression` fix your issue ?

**Comment by mathurinm** [comment]
Feel free to reopen if the issue is not fixed
