### ISSUE TITLE
DOC Objectives docstring do not use math mode

### ISSUE THREAD

**Issue by KishManani** [scikit-learn-contrib/skglm#144]
See: https://contrib.scikit-learn.org/skglm/generated/skglm.datafits.Poisson.html#skglm.datafits.Poisson

<img width="800" alt="image" src="https://user-images.githubusercontent.com/30973056/218250470-a147da51-f777-49fb-8ebe-e3670133c733.png">

**Comment by mathurinm** [comment]
Hi @KishManani, thanks for letting us know. Do you think you'd be able to send a PR fixing this, for example by looking at how it's fine in other classes where the rendering is correct ?
