### ISSUE TITLE
BUG error in prox slope computation

### ISSUE THREAD

**Issue by mathurinm** [scikit-learn-contrib/skglm#178]
for an array of constant alphas we should get that the SLOPE prox is a soft thresholding, because the penalty is just a Lasso

```python

from skglm.penalties import SLOPE
import numpy as np
np.random.seed(0)

d = 10
x = np.random.randn(d)
alphas = np.ones(10)
pen = SLOPE(alphas=alphas)
print(x)
print(pen.prox_vec(x, 1))
print(np.sign(x) * np.maximum(np.abs(x) - alphas[0], 0))
```

the last two outputs differ
```python
[ 1.764  0.4    0.979  2.241  1.868 -0.977  0.95  -0.151 -0.103  0.411]
[ 0.764  0.     1.241  1.241  0.868 -0.868  0.868 -0.    -0.868  0.868]
[ 0.764  0.     0.     1.241  0.868 -0.     0.    -0.    -0.     0.   ]
```

**Comment by mathurinm** [comment]
It's very surprising because we have [`test_slope_lasso` ](https://github.com/scikit-learn-contrib/skglm/blob/main/skglm/tests/test_penalties.py#L73)that shows the same results for SLOPE and Lasso when alpha is constant. :thinking: 

I checked that it does not return a vanishing solution

**Comment by Badr-MOUFAD** [comment]
Indeed, that's very weird. Normally they must be the same.
Can't say much, I need to delve into the implementation.
