### ISSUE TITLE
ENH get rid of our implementation of power method

### ISSUE THREAD

**Issue by mathurinm** [scikit-learn-contrib/skglm#183]
It seems it exists in scipy: https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.interpolative.estimate_spectral_norm.html 

let's just check that their implementation is faster and robust, but I'd be surprised if it wasn't :)

**Comment by Badr-MOUFAD** [comment]
That could have been great if we were able to use `scipy`, namely to reduce the code base leverages our dependencies.

I afraid,
1. it would not be possible as we call ``spectral_norm`` inside jitted classes
2. timing comparisons don't yield surprising results
![skglm-vs-scipy](https://github.com/scikit-learn-contrib/skglm/assets/65614794/9b2818af-c62f-491e-a667-aa177b066f61)
3. `scipy` uses a random estimate which doesn't yield a tight estimate of the spectral norm
