### ISSUE TITLE
FEAT - GroupLasso estimator with sparse X support

### ISSUE THREAD

**Issue by tomaszkacprzak** [scikit-learn-contrib/skglm#226]
## Description of the feature

Estimators that use `_glm_fit` already support sparse csc matrices. It would be great to have that for GroupLasso.
I think we should start with adding a new GroupLasso estimator. Would that also work with `_glm_fit` or do we anticipate any problems with calling this?

**Comment by mathurinm** [comment]
Hi @tomaszkacprzak, you'd need to implement a few methods for this to work, in `group_bcd.py` ; see the roadmap in https://github.com/scikit-learn-contrib/skglm/issues/197#issuecomment-1885202599

**Comment by mathurinm** [comment]
Great :rocket: ! 
You can already open a PR and mark it as draft, so you an get early feedback form the maintainers here 

Btw I see that you started working on your main branch ; I suggest you work on another branch instead:
- now your `main` branch and skglm `main` have diverged, so it will be harder to resynchronize when you're done on this pr
- in most repos, starting a PR gives maintainer push rights to the branch in question; you don't want us pushing to your `main` 
- working on `main` prevents you from working on several PRs simultaneously

**Comment by tomaszkacprzak** [comment]
Thank you for your help, I created a new branch on my fork and started a Draft Pull Request #228
