### ISSUE TITLE
Is AndersonCD solver compatible with Logistic datafit and L1 penalty ? 

### ISSUE THREAD

**Issue by egillax** [scikit-learn-contrib/skglm#227]
I've been experimenting with using the Anderson CD solver for logistic regression with the L1 penalty. Then I'm fitting a path (from alpha_max to alpha_max/100) on some random sparse data. But it's only fitting an intercept. 

Is this combination of solver/datafit/penalty expected to work?

**Comment by QB3** [comment]
Hello,
Can you provide a minimal reproducible example of your problem?
Also, you should be able to use the `ProxNewton` solver, which is usually faster for the logistic loss: this the default solver in the [`SparseLogisticRegression` estimator ](https://contrib.scikit-learn.org/skglm/generated/skglm.SparseLogisticRegression.html#skglm.SparseLogisticRegression)

**Comment by egillax** [comment]
>My guess it that it is computed for a model without intercept, and that the alpha max for a model with intercept (smallest value of alpha for which all coefs are 0 except the intercept) is much smaller.

@mathurinm thank you I think this was indeed the case. The alphas were to big, now I'm getting nonzero coefficients.
