### ISSUE TITLE
Generation of predicted values outside of the range [0,1]

### ISSUE THREAD

**Issue by ilanfri** [scikit-learn-contrib/skglm#230]
## Describe the bug

A trained model can predict negative scores, or scores larger than 1.

## Steps to reproduce
```
from skglm import ElasticNet
import nltk
import numpy as np
import pandas as pd
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer

nltk.download('names')

from nltk.corpus import names 

male_names = names.words('male.txt')
female_names = names.words('female.txt')

names_col = np.array(names.words('male.txt') + names.words('female.txt'))
label_col = np.hstack([np.zeros(len(names.words('male.txt')), dtype=int), np.ones_like(names.words('female.txt'), dtype=int)])

df = pd.DataFrame(data={'name':names_col, 'label':label_col}, dtype=(str, int))

df = df.sample(frac=1, random_state=5).reset_index(drop=True)

split_size = int(np.floor(df.shape[0]/3))

X_train = df.loc[:split_size, 'name'].values
X_val = df.loc[split_size:2*split_size, 'name'].values
X_test = df.loc[2*split_size:, 'name'].values

y_train = df.loc[:split_size, 'label'].values
y_val = df.loc[split_size:2*split_size, 'label'].values
y_test = df.loc[2*split_size:, 'label'].values

tfidf_params = {"strip_accents": "ascii", "analyzer": "char", "max_features": 30}
classifier_params = {'alpha':0.001, 'l1_ratio':0.001}

pipe = Pipeline([('tfidf', TfidfVectorizer(**tfidf_params)), ('elasticnet', ElasticNet(**classifier_params))])

pipe.fit(X_train, y_train)

pred = pipe.predict(X_val)

print(pred[pred < 0])
print(pred[pred > 1])
```

**Additional context**

The example above is entirely artificial and chosen purely based on the simplest labelled, open dataset I could get my hands on to replicate this issue, which we came across on an unrelated text-based problem internally, with data we cannot share.

Versions used:
Python 3.8.16

nltk==3.8.1
numpy==1.24.4
pandas==2.0.3
scikit_learn==1.3.2
skglm==0.3.1

**Comment by mathurinm** [comment]
Hi @ilanfri, you are using ElasticNet which is a model for **regression**, so the predicted value is continuous and can take any value.

Given that your `y` contains only 0s and 1s, it seems that you are looking for a model performing **classification**, that should for example be based on the [`Logistic`](https://contrib.scikit-learn.org/skglm/generated/skglm.datafits.Logistic.html) datafit, or the [`SparseLogisticRegression`](https://contrib.scikit-learn.org/skglm/generated/skglm.SparseLogisticRegression.html) estimator, to get output that only takes value 0 or 1.

**Comment by ilanfri** [comment]
Hi @mathurinm,

Indeed I am treating this as a regression problem where I expected the output to be continuous, but in the range (0,1), as it would be for a logit link function GLM. I would then proceed with a precision-recall analysis etc to choose a threshold, etc.

Indeed in this example you use ElasticNet on a binary dataset ('news20.binary', which I've never worked with myself but assume is binary from the name), so I assumed a logit link function was the default for ElasticNet:
https://github.com/scikit-learn-contrib/skglm/blob/main/examples/plot_compare_time.py

Otherwise indeed, an identity link function does not make sense for a binary classification task (though that's what seems to be done in the example).

Now I see from the documentation that ElasticNet by default actually uses the identity link function (which I would refer to as a linear model rather than a GLM, but conventions vary I suppose). So will use the SparseLogisticRegression module instead.

Thank you :)

**Comment by Badr-MOUFAD** [comment]
Thanks @ilanfri for your feedback

To answer your query, a dedicated issue #231 has been opened to add an elastic penalty to `SparseLogisticRegression` estimator.
In the meantime, you can settle with composing it

```python
# import datafit, penalty, and solver
from skglm.datafits import Logistic
from skglm.penalties import L1_plus_L2
from skglm.solvers import ProxNewton

from skglm.estimators import GeneralizedLinearEstimator


# build the elastic logistic regression estimator
estimator = GeneralizedLinearEstimator(
    datafit=Logistic(),
    penalty=L1_plus_L2(alpha=1., l1_ratio=0.7),
    solver=ProxNewton(fit_intercept=True)
)

# fit it on the dataset
estimator.fit(X, y)
```

If you don't mind, I will close the issue in favor of #231, feel free to reopen it for further inquires.

**Comment by ilanfri** [comment]
Hi @Badr-MOUFAD,

Brilliant! Thank you both for opening the feature request and for the custom way to build it in the meantime.

Yes of course, fine by me to close this issue :)

Kind regards,
Ilan

**Comment by ilanfri** [comment]
Thanks as well to @mathurinm!
