### ISSUE TITLE
FEAT - Support patsy built-in function for formula variable

### ISSUE THREAD

**Issue by hermanhmchan** [scikit-learn-contrib/skglm#248]
## Description of the feature

Can you support Patsy built-in function such as I(x) or Q(x)? It is supported in statsmodels.

**Additional context**

https://patsy.readthedocs.io/en/latest/builtins-reference.html

**Comment by mathurinm** [comment]
Hi @hermanhmchan, thanks for your interest. Can you describe your feature in more details, for example by providing a snippet of how it would be used?

**Comment by hermanhmchan** [comment]
Hi @mathurinm, thanks for your prompt reply. You can refer to https://www.statsmodels.org/stable/example_formulas.html for the use of formula.

For example, the dataframe has these columns: Lottery  Literacy  Wealth Region.
```
In [7]: df.head()
Out[7]: 
   Lottery  Literacy  Wealth Region
0       41        37      73      E
1       38        51      22      N
2       66        13      61      C
3       80        46      76      E
4       79        69      83      E`
```
We can use formula instead of simply specifying the columns.
```
In [8]: res = smf.ols(formula='Lottery ~ Literacy + Wealth + Region', data=df).fit()
In [11]: res = smf.ols(formula='Lottery ~ Literacy + Wealth + C(Region)', data=df).fit()
In [13]: res = smf.ols(formula='Lottery ~ Literacy + Wealth + C(Region) -1 ', data=df).fit()
In [15]: res1 = smf.ols(formula='Lottery ~ Literacy : Wealth - 1', data=df).fit()
In [16]: res2 = smf.ols(formula='Lottery ~ Literacy * Wealth - 1', data=df).fit()
In [19]: res = smf.ols(formula='Lottery ~ np.log(Literacy)', data=df).fit()
```

**Comment by mathurinm** [comment]
Rahter than statsmodel we are more inspired by the sklearn API which does not support such formulas. Unless there is a strong demand we do not plan on implementing it at the moment and I'll close the issue.
