### ISSUE TITLE
DOC - Add tutorial for Group Estimators

### ISSUE THREAD

**Issue by Badr-MOUFAD** [scikit-learn-contrib/skglm#263]
**Description of the feature**

Now that [Group-lasso](https://github.com/yngvem/group-lasso) package is pointing towards skglm,
having a starter example that exposes the capabilities of skglm in dealing with Group-structure problems will be very handy for the practitioners.

**Additional context**

See https://github.com/yngvem/group-lasso/pull/40

**Comment by mathurinm** [comment]
We have it here ! https://contrib.scikit-learn.org/skglm/auto_examples/plot_group_logistic_regression.html#sphx-glr-auto-examples-plot-group-logistic-regression-py

Feel free to improve the example

**Comment by yngvem** [comment]
I must have missed that completely when I looked at the docs, amazing! I'll merge the PR on the group-lasso repo then :)
