### ISSUE TITLE
BUG - code breaks down whithout throwing any error when calling ``cd_solver``

### ISSUE THREAD

**Issue by Badr-MOUFAD** [scikit-learn-contrib/skglm#35]
## Script to reproduce

```python
import numpy as np
from skglm.datafits import Quadratic
from skglm.penalties import L1
from skglm.solvers.cd_solver import cd_solver
from skglm.utils import make_correlated_data

n_samples, n_features = 10, 50
X, y, _ = make_correlated_data(n_samples, n_features, random_state=0)
alpha_max = np.linalg.norm(X.T @ y, ord=np.inf) / n_samples

datafit = Quadratic()
penalty = L1(alpha=alpha_max / 10.)

w = np.zeros(n_features)
Xw = np.zeros(n_samples)
cd_solver(X, y, datafit, penalty, w, Xw)

print("This line will never be printed")
print("This one also will never be printed")
print("...")
```

This is a dangerous behavior as the code breaks without giving any hint on what's wrong (even with a debugger).

## source of the bug and a potential fix

After debugging, I find out that the problem emanates from passing in a non-initialized ``datafit`` to ``cd_solver``. In fact, the solver attempts to access the Lipschitz constants of datafit to compute grads, which doesn't exist. 

**A natural way to fix this bug is to make ``cd_solver`` a private member to prevent calling it directly from the outside**.

## Reflections

Not having the Lipschitz constant doesn't explain why the code breaks without throwing any error. I suspect a bug in ``Numba`` compilation and here is a small script to reproduce the bug

```python
import numpy as np
from numba import float64
from numba.experimental import jitclass

@jitclass([('Xty', float64[:])])
class Quadratic:
    def __init__(self):
        pass

    def gradient_scalar(self, X, Xw, j):
        return (X[:, j] @ Xw - self.Xty[j]) / len(Xw)

X = np.ones((2, 5))
Xw = np.zeros(2)

Quadratic().gradient_scalar(X, Xw, 0)

print("This line will never be printed")
```

**Comment by PABannier** [comment]
Indeed, it's a dangerous behavior and we're not warning the user.
I can reproduce the bug: I face a segmentation fault.
The natural fix would be to check with `hasattr` if `Xty` exists (hence if `initialize` has been called), but Numba is not able to compile / recognize built-in Python functions.

**Comment by mathurinm** [comment]
I don't see a cheap way of checking it everytime you call a method of Datafit
I'd make cd_solver private instead

**Comment by Badr-MOUFAD** [comment]
Closing as it was fixed (cf. https://github.com/numba/numba/issues/8194).
