### ISSUE TITLE
ENH skglm import time is high

### ISSUE THREAD

**Issue by mathurinm** [scikit-learn-contrib/skglm#46]
```
In [1]: import time

In [2]: t0 = time.time()
   ...: import skglm
   ...: 
   ...: print(time.time() - t0)
0.7723352909088135
```
I thought this was due to numba compilation, but it's not fixed on #44. importing Lasso from sklearn.linear_model takes 1e-5 s, that is weird

**Comment by Badr-MOUFAD** [comment]
I think it has to do more with importing our dependencies, namely, numba, sklearn, scipy among others.

Through the example below I managed to reduce the import time to 0.15 on my local machine.

```python
import time

start = time.time()
import scipy
end = time.time()
print(f"time to import scipy: {end - start}")

start = time.time()
import sklearn
end = time.time()
print(f"time to import scikit learn: {end - start}")

start = time.time()
import numba
end = time.time()
print(f"time to import numba: {end - start}")

start = time.time()
import skglm
end = time.time()
print(f"time to import skglm: {end - start}")
```

Ouput 

```console
time to import scipy: 0.16607046127319336
time to import scikit learn: 0.4579463005065918
time to import numba: 0.2870755195617676
time to import skglm: 0.14461469650268555
```

**Comment by PABannier** [comment]
<img width="827" alt="Screen Shot 2022-07-27 at 11 11 05 AM" src="https://user-images.githubusercontent.com/12958149/181209554-3c3fd6f7-03a8-4c10-a61e-bd73dd820d4b.png">

Difficult to say. Prefer to use `-X importtime` flags in Python interpreter for a better visualization of import times
