### ISSUE TITLE
How to control number of cores?

### ISSUE THREAD

**Issue by s-banach** [scikit-learn-contrib/skglm#48]
I apologize for opening an issue that isn't a real bug.

I need to control the number of cores used when I fit a model.
I've tried the following things:
(1)
```python
from numba import set_num_threads
set_num_threads(1)
```
(2)
```python
from numba import config
config.NUMBA_NUM_THREADS = 1
```
(3) Going through the source code and replacing every instance of `@njit` with `@njit(parallel=False)`.

No matter what I try, I see my core usage shoot up to 128.
I'm on a cluster of machines connected by slow interconnect, so this core usage actually makes the model run very slow.
Does anybody understand how to control this?

**Comment by QB3** [comment]
Hello @s-banach ,
Thanks a lot for interest! As a dirty trick I always add

`export MKL_NUM_THREADS=1
export NUMEXPR_NUM_THREADS=1
export OMP_NUM_THREADS=1
`

in my .bashrc file. Is this fixing your problem?

**Comment by s-banach** [comment]
Thanks for the answer!

For my own use, I googled "OMP_NUM_THREADS" and found this post: https://stackoverflow.com/a/53224849
It basically says "you can configure the number of cores before importing `numpy`, after that you can't do anything".
I would like to run a linear model inside a package I'm writing, and be able to control the number of cores used regardless of what else the user has imported or how they have configured their environment.

I don't suppose there's any way I can do  that, other than telling the end user "Configure your environment variables correctly before you run the package." :(

**Comment by s-banach** [comment]
I just discovered threadpoolctl, so that should help somewhat. 😄
