### ISSUE TITLE
ENH add BaseSolver class, transform cd_solver and pn_solver into classes 

### ISSUE THREAD

**Issue by mathurinm** [scikit-learn-contrib/skglm#61]
it will be easier to pass instances of such classes to GeneralizedLinearEstimator (currently the solvers are hardcoded), and it will simplify the API.

**Comment by QB3** [comment]
Do we have to fully jit `cd_solver` or `pn_solver`? (I guess yes).
But this might be more painful to debug / profile.

**Comment by mathurinm** [comment]
In fact there is no reason to jit the solver classes, I realized. I left the `get_spec` and other methods, but you can see that the solver works fast without being jitted

Same for cd solver, since it's currently not jitted (only critical parts are), it should be easy to put into a class

**Comment by mathurinm** [comment]
closed by #63
