### ISSUE TITLE
DOC update citation in README and doc

### ISSUE THREAD

**Issue by mathurinm** [scikit-learn-contrib/skglm#83]
we are no longer a `@online` but a `@inproceedings` :)

**Comment by Badr-MOUFAD** [comment]
Change ``@online`` to ``@inproceedings`` in
- [README](https://github.com/scikit-learn-contrib/skglm#cite)
- [Documentation](https://github.com/scikit-learn-contrib/skglm/blob/main/doc/index.rst#cite)
